CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, username TEXT NOT NULL, password_hashed TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS food_items (id SERIAL PRIMARY KEY, name TEXT NOT NULL, calories INTEGER NOT NULL, notes TEXT, created_at DATE NOT NULL DEFAULT CURRENT_DATE, user_id INTEGER REFERENCES users(id) NOT NULL);